let data = [
  {
    id: 1,
    img: "img1.jpg",
    title: "수국 디퓨저",
    content: "내추럴 플라워 라인 6가지 향",
    price: "9,900",
    list: "d",
  },
  {
    id: 2,
    img: "img2.jpg",
    title: "플라워 캔들",
    content: "플라워 디퓨저 120ml",
    price: "15,900",
    list: "k",
  },
  {
    id: 3,
    img: "img3.jpg",
    title: "미스티블루 디퓨저",
    content: "미니 플라워 라인 2가지 향",
    price: "14,900",
    list: "d",
  },
  {
    id: 4,
    img: "img4.jpg",
    title: "하바리움캔들",
    content: "하바리움캔들 + 리필액",
    price: "12,900",
    list: "k",
  },
  {
    id: 5,
    img: "img5.jpg",
    title: "수국 캔들 ",
    content: "내추럴 플라워 라인 6가지 향",
    price: "9,900",
    list: "k",
  },
  {
    id: 6,
    img: "img6.jpg",
    title: "플라워 디퓨저",
    content: "플라워 디퓨저 120ml",
    price: "15,900",
    list: "d",
  },
  {
    id: 7,
    img: "img7.jpg",
    title: "미스티블루 캔들",
    content: "미니 플라워 라인 2가지 향",
    price: "14,900",
    list: "k",
  },
  {
    id: 8,
    img: "img8.jpg",
    title: "하바리움 디퓨저",
    content: "하바리움 디퓨저 + 리필액",
    price: "12,900",
    list: "d",
  },
  {
    id: 9,
    img: "img1.jpg",
    title: "수국 디퓨저2",
    content: "내추럴 플라워 라인 6가지 향",
    price: "9,900",
    list: "d",
  },
  {
    id: 10,
    img: "img2.jpg",
    title: "플라워 캔들2",
    content: "플라워 디퓨저 120ml",
    price: "15,900",
    list: "k",
  },
  {
    id: 11,
    img: "img3.jpg",
    title: "미스티블루 디퓨저2",
    content: "미니 플라워 라인 2가지 향",
    price: "14,900",
    list: "d",
  },
  {
    id: 12,
    img: "img4.jpg",
    title: "하바리움캔들2",
    content: "하바리움캔들 + 리필액",
    price: "12,900",
    list: "k",
  },
  {
    id: 13,
    img: "img5.jpg",
    title: "수국 캔들2 ",
    content: "내추럴 플라워 라인 6가지 향",
    price: "9,900",
    list: "k",
  },
  {
    id: 14,
    img: "img6.jpg",
    title: "플라워 디퓨저2",
    content: "플라워 디퓨저 120ml",
    price: "15,900",
    list: "d",
  },
  {
    id: 15,
    img: "img7.jpg",
    title: "미스티블루 캔들2",
    content: "미니 플라워 라인 2가지 향",
    price: "14,900",
    list: "k",
  },
  {
    id: 16,
    img: "img8.jpg",
    title: "하바리움 디퓨저2",
    content: "하바리움 디퓨저 + 리필액",
    price: "12,900",
    list: "d",
  },
];

export default data;
